# Generated by Django 3.2.3 on 2021-05-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('special', 'Special'), ('snack', 'Snack'), ('side', 'Side')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
